apiVersion: apps/v1
kind: Deployment 
metadata:
  name: helloworld-api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:  
    metadata:
      labels: 
        app: api
    spec:
      containers:
        - name: helloworld-api
          image: akkineniramana/helloworld-api:1.0
          ports: 
            - containerPort: 5000           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "api"            
            - name: DB_USERNAME
              value: "root"            
            - name: DB_PASSWORD
              value: "root"     